CheatSheet/CheatSheet/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from htmlCheatSheet.views import HtmlModelListView, about
from django.contrib.auth import views
urlpatterns = [
    url(r'^$', HtmlModelListView.as_view(), name='index'),
    url(r'^about/', about, name='about'),
    url(r'^html/', include('htmlCheatSheet.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'accounts/login/$', views.login, name='login'),
    url(r'account/logout/$', views.logout,
        name='logout', kwargs={'next_page': '/'}),
]

CheatSheet/htmlCheatSheet/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from htmlCheatSheet import views
app_name = 'htmlCheatSheet'
urlpatterns = [
    url(r'^$', views.HtmlCheatPage.as_view(), name='htmlpage'),
    url(r'^new/', views.CreateHtmlModelView.as_view(), name="post_new"),
    url(r'^list', views.HtmlModelListView.as_view(), name='htmllist'),
    url(r'^cheat/(?P<pk>\d+)$',
        views.HtmlModelDetailView.as_view(), name='cheat_detail'),
    url(r'^cheat/(?P<pk>\d+)/edit/$',
        views.HtmlModelUpdateView.as_view(), name='cheat_edit'),
    url(r'^cheat/(?P<pk>\d+)/delete/$',
        views.HtmlModelDeleteView.as_view(), name='cheat_delete'),
]

CheatSheet/cssCheatSheet/models.py
from django.db import models

# Create your models here.

CheatSheet/htmlCheatSheet/models.py
from django.db import models
from django.core.urlresolvers import reverse
# Create your models here.


class HtmlModel(models.Model):
    title = models.CharField(max_length=256)
    description = models.TextField()
    example_html = models.TextField()

    def get_absolute_url(self):
        return reverse("htmlCheatSheet:cheat_detail", kwargs={'pk': self.pk})

    def min_text(self):
        x = min(50, len(self.description))
        return self.description[:x]

    def __str__(self):
        return self.title


class CommentModel(models.Model):
    html = models.ForeignKey(
        'htmlCheatSheet.HtmlModel', related_name='comments')
    author = models.CharField(max_length=256)
    text = models.TextField()

    def __str__(self):
        return self.text

CheatSheet/jsCheatSheet/models.py
from django.db import models

# Create your models here.

CheatSheet/htmlCheatSheet/forms.py
from django import forms
from django.forms import ModelForm, fields
from htmlCheatSheet.models import HtmlModel, CommentModel


class HtmlModelForm(ModelForm):

    class Meta:
        model = HtmlModel
        fields = ('title', 'description', 'example_html')


class CommentModelForm(ModelForm):

    class Meta:
        model = CommentModel
        fields = ('author', 'text')

CheatSheet/cssCheatSheet/views.py
from django.shortcuts import render

# Create your views here.

CheatSheet/htmlCheatSheet/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import (
    TemplateView, CreateView, ListView, DetailView, UpdateView, DeleteView)
from htmlCheatSheet.models import HtmlModel
from htmlCheatSheet.forms import HtmlModelForm, CommentModelForm
from django.views.generic.edit import FormMixin
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
# Create your views here.


def about(request):
    context = {
        'github': "https://github.com/FazleRabbbiferdaus172",
        "linkedin": "https://www.linkedin.com/in/fazle-rabbi-ferdaus-113255185/"
    }
    return render(request, 'about.html', context=context)


class HtmlCheatPage(TemplateView):
    template_name = 'htmlCheatSheet/htmlCheatPage.html'


class HtmlModelListView(ListView):
    model = HtmlModel
    template_name = 'htmlCheatSheet/htmlCheatPageList.html'


class CreateHtmlModelView(LoginRequiredMixin, CreateView):
    login_url = '/login/'
    redirect_field_name = 'htmlCheatSheet/htmlCheatPagedetail.html'
    form_class = HtmlModelForm
    model = HtmlModel
    template_name = 'htmlCheatSheet/htmlmodel_form.html'


class HtmlModelUpdateView(LoginRequiredMixin, UpdateView):
    login_url = '/login/'
    redirect_field_name = 'htmlCheatSheet/htmlCheatPagedetail.html'
    form_class = HtmlModelForm
    model = HtmlModel


class HtmlModelDeleteView(LoginRequiredMixin, DeleteView):
    model = HtmlModel
    success_url = reverse_lazy('htmlCheatSheet:htmllist')


class HtmlModelDetailView(FormMixin, DetailView):
    model = HtmlModel
    form_class = CommentModelForm
    template_name = 'htmlCheatSheet/htmlCheatPagedetail.html'

    def get_success_url(self):
        return reverse('htmlCheatSheet:cheat_detail', kwargs={'pk': self.object.pk})

    def post(self, request, *args, **kwargs):

        self.object = self.get_object()

        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        # Here, we would record the user's interest using the message
        # passed in form.cleaned_data['message']
        html = get_object_or_404(HtmlModel, pk=self.object.pk)
        comment = form.save(commit=False)
        comment.html = html
        comment.save()
        return super().form_valid(form)

CheatSheet/jsCheatSheet/views.py
from django.shortcuts import render

# Create your views here.

CheatSheet/templates/about.html
{% extends 'base.html' %}
{% block content %}
    <div class="about">
    <h1>About This Website</h1>
    <p>This a website for creating cheat sheets for HTML, CSS and JavaScript. Only the users can create cheat sheets and visitors watch, learn and play with the cheatsheets. Thank you for visiting        
    </p>
    </div>
    <div class="contact">
        <h1>How to find me</h1>
        <h2><a href={{ github }}>Github</a></h2>
        <h2><a href={{ linkedin }}>Linkedin</a></h2>

    </div>
{% endblock %}

CheatSheet/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Nova+Mono&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static "css/cheatsheet.css" %}">
    <title>CheatSheet</title>
</head>
<body>
    <ul class="nav nav-tabs">
        <li class="nav-item">
          <a class="nav-link baseButton primaryButton" aria-current="page" href="{% url 'htmlCheatSheet:htmllist' %}">HTML</a>
        </li>
        <li class="nav-item">
          <a class="nav-link  baseButton primaryButton" href="#">CSS</a>
        </li>
        <li class="nav-item">
          <a class="nav-link  baseButton primaryButton" href="#">JS</a>
        </li>
        <li class="nav-item">
          <a class="nav-link  baseButton primaryButton" href="{% url 'about' %}">About</a>
        </li>

        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link baseButton primaryButton" href="{% url 'htmlCheatSheet:post_new' %}" >New Post</a>
        </li>
        <li class="nav-item">
          <a class="nav-link baseButton primaryButton" href="{% url 'logout' %}" >Log out</a>
        </li>

        <li class="nav-item">
          <a class="nav-link baseButton primaryButton" >Welcome: {{ user.username }}</a>
        </li class="nav-item">
          {% else %}
          <li><a class="nav-link baseButton primaryButton"  href="{% url 'login' %}" >Login</a></li>
        {% endif %}
      </ul>
    

      <div class="container">
        {% block content %}
        {% endblock %}
      </div>
      <script>
        function htmlToElements(html) {
            var template = document.createElement('template');
            template.innerHTML = html;
            return template.content.childNodes;
        }
        const run = (e) => {
            //console.log(e.value);
            const html = e.previousElementSibling;
            //console.log(html); 
            const scrn = html.parentElement.nextElementSibling;
            var add = document.createElement('h1');
            //add.innerHTML = "hi"
            //console.log(scrn);
            //scrn.appendChild(add);
            htmlTodo = html.value.trim();
            //console.log(htmlTodo);
            const nodeList = htmlToElements(htmlTodo);
            const div = document.createElement('div');
            nodeList.forEach(element => {
                div.appendChild(element)
            });
            scrn.innerText = ""
            scrn.appendChild(div)
    }
</script>

</body>
</html>

CheatSheet/templates/htmlCheatSheet/htmlCheatPageList.html
{% extends 'base.html' %}
{% block content %}
    {% if htmlmodel_list %}
        {% for i in htmlmodel_list %}
            <div class="cheatpost">
                <h1><a href="{% url 'htmlCheatSheet:cheat_detail' pk=i.pk %}" class="listtitle">
                    {{ i.title }}
                </a></h1>
                <p>{{ i.min_text }}</p>
                {% if user.is_authenticated %}
                <a href="{% url 'htmlCheatSheet:cheat_edit' pk=i.pk %}" class="btn btn-primary">Edit</a>
                <a href="{% url 'htmlCheatSheet:cheat_delete' pk=i.pk %}" class="btn btn-primary btn-warning">Delete</a>
                {% endif %}
            </div>
        {% endfor %}
    {% else %}
        <h1>No CheatSheet</h1>
    {% endif %}
{% endblock %}

CheatSheet/templates/htmlCheatSheet/htmlCheatPagedetail.html
{% extends 'base.html' %}
{% block content %}
    <h1>{{ htmlmodel.title }}</h1>
    <p>{{ htmlmodel.description|safe|linebreaksbr }}</p>
    <div class="flex-container">
        <div class="text-editor ">
            <textarea name="input" class="noscroll" id="" cols="30" rows="10">{{ htmlmodel.example_html }}</textarea>
            <input type="button" value="run" onclick="run(this)">
        </div>
        <div class="screen noscroll">
        </div>
    </div>
    <div class="comment-container">
        <h1>Comment Section</h1>
        <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Add comment</button>
        </form>
    </div>
    <div class="container flex-comment">
        {% for comment in htmlmodel.comments.all %}
            <div class="comment-card">
            <p>{{ comment.text|safe|linebreaks }}</p>
            <h3>Posted By: {{ comment.author }}</h3>
            </div>
        {% endfor %}
    </div>
{% endblock %}

CheatSheet/templates/htmlCheatSheet/htmlcheatpage.html
{% extends 'base.html' %}
{% block content %}
    <div class="flex-container">
        <div class="text-editor">
            <textarea name="input" id="" cols="30" rows="10"><H1>ME0NE</H1></textarea>
            <input type="button" value="run" onclick="run(this)">
        </div>
        <div class="screen">
        </div>
    </div>

    <div class="flex-container">
        <div class="text-editor">
            <textarea name="input" id="" cols="30" rows="10"><H1>MET00</H1></textarea>
            <input type="button" value="run" onclick="run(this)">
        </div>
        <div class="screen scrollbar" id="style-9">
        </div>
    </div>
    <!--<script>
            function htmlToElements(html) {
                var template = document.createElement('template');
                template.innerHTML = html;
                return template.content.childNodes;
            }
        const run = (e) => {
            //console.log(e.value);
            const html = e.previousElementSibling;
            //console.log(html); 
            const scrn = html.parentElement.nextElementSibling;
            var add = document.createElement('h1');
            //add.innerHTML = "hi"
            //console.log(scrn);
            scrn.appendChild(add);
            //htmlTodo = html.value.trim();
            //console.log(htmlTodo);
            const nodeList = htmlToElements(htmlTodo);
            const div = document.createElement('div');
            nodeList.forEach(element => {
                div.appendChild(element)
            });
            scrn.appendChild(div)
        }
    </script>-->
{% endblock %}

CheatSheet/templates/htmlCheatSheet/htmlmodel_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete {{ object }} ?</p>
        <input type="submit"  class="btn btn-danger" value="confirm">
    </form>
{% endblock %}

CheatSheet/templates/htmlCheatSheet/htmlmodel_form.html
{% extends 'base.html' %}
{% block content %}
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Post</button>
</form>
{% endblock %}